In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:/Users/nn/Downloads/gender/gender_classification_v7.csv")

In [3]:
df.head()

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0          1               11.8                 6.1          1          0   
1          0               14.0                 5.4          0          0   
2          0               11.8                 6.3          1          1   
3          0               14.4                 6.1          0          1   
4          1               13.5                 5.9          0          0   

   lips_thin  distance_nose_to_lip_long  gender  
0          1                          1    Male  
1          1                          0  Female  
2          1                          1    Male  
3          1                          1    Male  
4          0                          0  Female

In [4]:
df.drop(columns=["forehead_width_cm","forehead_height_cm"],inplace=True)


In [5]:
df.isnull().sum()

long_hair                    0
nose_wide                    0
nose_long                    0
lips_thin                    0
distance_nose_to_lip_long    0
gender                       0
dtype: int64

In [6]:
df["gender"] = df["gender"].replace(["Male","Female"],[0,1])

In [7]:
df.head()

long_hair  nose_wide  nose_long  lips_thin  distance_nose_to_lip_long  \
0          1          1          0          1                          1   
1          0          0          0          1                          0   
2          0          1          1          1                          1   
3          0          0          1          1                          1   
4          1          0          0          0                          0   

   gender  
0       0  
1       1  
2       0  
3       0  
4       1

In [8]:
X = df.drop(columns=["gender"])
y = df["gender"]

classification

In [9]:
#train test split

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20)

In [11]:
#KNN

In [12]:
from sklearn.neighbors import KNeighborsClassifier

In [13]:
knn = KNeighborsClassifier()

In [14]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [15]:
y_predict = knn.predict(X_test)

In [16]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predict)
print ("cm :", cm)



cm : [[477  22]
 [ 10 492]]


In [17]:
from sklearn.metrics import classification_report
cr = classification_report(y_test,y_predict)
print ("cr :",cr)

cr :               precision    recall  f1-score   support

           0       0.98      0.96      0.97       499
           1       0.96      0.98      0.97       502

    accuracy                           0.97      1001
   macro avg       0.97      0.97      0.97      1001
weighted avg       0.97      0.97      0.97      1001



In [18]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,y_predict)
print("accuracy :", accuracy)

accuracy : 0.968031968031968


## Random forest

In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
rand_forest = RandomForestClassifier()

In [21]:
rand_forest.fit(X_train,y_train)

RandomForestClassifier()

In [22]:
rf_predict = rand_forest.predict(X_test)


In [23]:
rf_predict

array([1, 1, 1, ..., 1, 0, 0], dtype=int64)

In [24]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,rf_predict)

In [25]:
cm

array([[485,  14],
       [ 28, 474]], dtype=int64)

In [26]:
from sklearn.metrics import classification_report
cr= classification_report(y_test,rf_predict)

In [27]:
print(cr)

              precision    recall  f1-score   support

           0       0.95      0.97      0.96       499
           1       0.97      0.94      0.96       502

    accuracy                           0.96      1001
   macro avg       0.96      0.96      0.96      1001
weighted avg       0.96      0.96      0.96      1001



In [28]:
from sklearn.metrics import accuracy_score
a_score = accuracy_score(y_test,rf_predict)

In [29]:
a_score

0.958041958041958

## AdaBoost

In [30]:
from sklearn.ensemble import AdaBoostClassifier

In [31]:
adaboost = AdaBoostClassifier()

In [32]:
adaboost.fit(X_train,y_train)

AdaBoostClassifier()

In [33]:
ada_predict = adaboost.predict(X_test)

In [34]:
from sklearn.metrics import confusion_matrix

In [35]:
cm = confusion_matrix(y_test,ada_predict)

In [36]:
cm

array([[493,   6],
       [ 43, 459]], dtype=int64)

In [37]:
from sklearn.metrics import classification_report

In [38]:
cr = classification_report(y_test,ada_predict)

In [39]:
print(cr)

              precision    recall  f1-score   support

           0       0.92      0.99      0.95       499
           1       0.99      0.91      0.95       502

    accuracy                           0.95      1001
   macro avg       0.95      0.95      0.95      1001
weighted avg       0.95      0.95      0.95      1001



In [44]:
from sklearn.metrics import accuracy_score

In [45]:
accuracy = accuracy_score(y_test,ada_predict)

In [46]:
accuracy

0.951048951048951